services:
  mariadb:
    build: ./srcs/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network

  wordpress:
    build: ./srcs/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - network
    # secrets:
    #   - wp_second_user_password

  nginx:
    build: ./srcs/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - network

  ftp:
    build: ./srcs/ftp
    image: ftp
    container_name: ftp
    restart: always
    env_file: .env
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wp_data:/var/www/html
    networks:
      - network

  redis:
    build: ./srcs/redis
    image: redis
    container_name: redis
    restart: always
    networks:
      - network

  adminer:
    build: ./srcs/adminer
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - network

  vueapp:
    build: ./srcs/vueapp
    image: vueapp
    container_name: vueapp
    restart: always
    ports:
      - "8080:80"   # сайт доступен на 8080
    networks:
      - network

  profile:
    build: ./srcs/profile
    container_name: profile
    image: profile
    restart: always
    ports:
      - "8081:80"   # сайт доступен на 8081
    networks:
      - network
  portainer:
      build: ./srcs/portainer
      container_name: portainer
      restart: unless-stopped
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      networks:
        - network

  site_monitor:
    build: ./srcs/site_monitor
    container_name: site_monitor
    restart: always
    env_file: .env
    networks:
      - network

  uptime:
    build: ./srcs/uptime
    container_name: uptime
    restart: unless-stopped
    ports:
      - "3002:3001"
    volumes:
      - uptime_data:/app/data
    networks:
      - network

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sskobyak/data/db
      o: bind

  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sskobyak/data/wp
      o: bind

  portainer_data:
  uptime_data:

networks:
  network:
    driver: bridge

# secrets:
#   wp_second_user_password:
#     external: true    